.PHONY: run test tidy

PORT ?= 8080
READ_TIMEOUT_SEC ?= 5
WRITE_TIMEOUT_SEC ?= 10
IDLE_TIMEOUT_SEC ?= 60
SHUTDOWN_TIMEOUT_SEC ?= 10

run:
	PORT=$(PORT) READ_TIMEOUT_SEC=$(READ_TIMEOUT_SEC) WRITE_TIMEOUT_SEC=$(WRITE_TIMEOUT_SEC) IDLE_TIMEOUT_SEC=$(IDLE_TIMEOUT_SEC) SHUTDOWN_TIMEOUT_SEC=$(SHUTDOWN_TIMEOUT_SEC) go run ./cmd/api

test:
	go test ./... -count=1

tidy:
	go mod tidy

